In [ ]:
import pandas as pd
import numpy as np


In [ ]:
message=pd.read_csv("dataset.csv")

In [ ]:
message.head()

prompt  label
0           Can you help me understand this concept?      1
1  I'm having trouble with my assignment. Can you...      1
2          Please explain how to solve this problem.      1
3     Could you provide some guidance on this topic?      1
4        What are the steps to follow for this task?      1

In [ ]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['prompt'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['help understand concept',
 'troubl assign assist',
 'pleas explain solv problem',
 'could provid guidanc topic',
 'step follow task',
 'lost point right direct',
 'stuck provid advic',
 'need assist project',
 'use softwar',
 'clarifi instruct',
 'done research still unsur help',
 'need someon review work',
 'pleas explain equat',
 'check solut correct',
 'struggl understand paragraph',
 'need help brainstorm idea essay',
 'key point focu',
 'could explain main concept chapter',
 'recommend resourc studi',
 'need help organ thought',
 'improv write skill',
 'writer block help overcom',
 'assist prepar exam',
 'overwhelm break',
 'pleas provid feedback present',
 'need help choos topic research paper',
 'suggest thesi statement essay',
 'confus requir assign clarifi',
 'troubl find reliabl sourc help',
 'cite sourc apa format',
 'sure conclus strong enough advis',
 'need help understand implic theori',
 'could explain signific experi',
 'struggl interpret result assist',
 'need help c

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features=100)
X = cv.fit_transform(corpus).toarray()

y=pd.get_dummies(message['label'])
y=y.iloc[:,1].values

In [ ]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
y.shape

(223,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [ ]:
y_pred=spam_detect_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming y_test and y_pred are your actual and predicted labels respectively
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 1.0


In [ ]:
from sklearn.model_selection import cross_val_score, KFold
# Define the number of folds for cross-validation
num_folds = 5  # You can adjust this as needed

# Define the cross-validation strategy
kfold = KFold(n_splits=num_folds, shuffle=True, random_state=42)

# Perform cross-validation
cv_scores = cross_val_score(spam_detect_model, X_train, y_train, cv=kfold)

# Print the cross-validation scores
print("Cross-validation scores:", cv_scores)

# Calculate and print the average cross-validation score
print("Average Cross-validation score:", cv_scores.mean())

Cross-validation scores: [0.97222222 0.94444444 1.         1.         0.91428571]
Average Cross-validation score: 0.9661904761904762


In [ ]:
sentence="do my assignment"

In [ ]:
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['prompt'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
def predict_sentence(sentence, vectorizer, classifier):
    # Preprocess the input sentence
    review = re.sub('[^a-zA-Z]', ' ', sentence)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)

    # Fit the CountVectorizer on the training data if not already fitted
    if not hasattr(vectorizer, 'vocabulary_'):
        vectorizer.fit(corpus)  # Assuming 'corpus' is your preprocessed text data

    # Transform the preprocessed sentence into a numerical feature vector
    sentence_vector = vectorizer.transform([review]).toarray()

    # Use the trained classifier to predict the label for the preprocessed sentence
    predicted_label = classifier.predict(sentence_vector)

    return predicted_label

# Example usage:
predicted_label = predict_sentence("complete my code", cv, spam_detect_model)
print("Predicted Label:", predicted_label)


Predicted Label: [0]


In [ ]:
from joblib import dump

# Save the trained model to a file
dump(spam_detect_model, 'spam_detection_model.joblib')

['spam_detection_model.joblib']

In [ ]:
from joblib import load

# Load the saved model from the file
loaded_model = load('spam_detection_model.joblib')

In [ ]:
def predict_sentence(sentence, vectorizer, classifier):
    # Preprocess the input sentence
    review = re.sub('[^a-zA-Z]', ' ', sentence)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)

    # Fit the CountVectorizer on the training data if not already fitted
    if not hasattr(vectorizer, 'vocabulary_'):
        vectorizer.fit(corpus)  # Assuming 'corpus' is your preprocessed text data

    # Transform the preprocessed sentence into a numerical feature vector
    sentence_vector = vectorizer.transform([review]).toarray()

    # Use the trained classifier to predict the label for the preprocessed sentence
    predicted_label = classifier.predict(sentence_vector)

    return predicted_label

# Example usage:
predicted_label = predict_sentence("help me write my assignment", cv, loaded_model)
print("Predicted Label:", predicted_label)


Predicted Label: [1]


In [ ]:
!pip install openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 262.4/262.4 kB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.5 MB/s eta 0:00:00


In [ ]:
import os
from openai import OpenAI

# Set OpenAI API key programmatically
os.environ["OPENAI_API_KEY"] = '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'

# Set OpenAI API key for the OpenAI client
OpenAI.api_key = os.getenv('OPENAI_API_KEY')

client = OpenAI()

completion = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "tell me about python"}
    ]
)

print(completion.choices[0].message.content)
